# TODO: Restart always unless manually stopped
name: webserver-plus-reverse-proxy-container
version: "3"
services:
    webserver:
        build: .
        environment:
            - TERM=xterm-256color
        ports:
            - "3000:3000"
    reverse-proxy:
        image: caddy:latest
        environment:
            - TERM=xterm-256color
        cap_add:
            - NET_ADMIN
        depends_on:
            - webserver
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - $PWD/Caddyfile:/etc/caddy/Caddyfile
            - config:/config
            - data:/data

volumes:
    config:
    data:
